version: '3.0'

volumes:
  frontend-files:
    driver_opts:
      type: none
      device: ${PWD}/frontend/app
      o: bind
  backend-files:
    driver_opts:
      type: none
      device: ${PWD}/backend
      o: bind

services:

  frontend:
    build: ./frontend/config
    container_name: ft_frontend
    ports:
      - "443:443"
    volumes:
      - frontend-files:/var/www

  backend:
    build: ./backend
    container_name: ft_backend
    ports:
      - "8000:8000"
    volumes:
      - backend-files:/app
    
    