version: '3.4'

networks:
  trans:

services:

  frontend:
    build: ./frontend/config
    container_name: ft_frontend
    ports:
      - "443:443"
      - "4009:80"
    volumes:
      - ./frontend/app:/var/www
    environment:
      - BACKEND_HOST=localhost
    network_mode: host

  db:
    image: postgres:latest
    container_name: ft_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5432:5432"
    restart: always
    networks:
      - trans

  redis:
    image: redis:latest
    container_name: ft_redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "6379:6379"
    networks:
      - trans

  game_loop:
    build: ./game_loop
    container_name: ft_game_loop
    environment:
      - BACKEND_HOST=localhost
      - BACKEND_PORT=${BACKEND_PORT}
    network_mode: host