version: '3.4'

networks:
  trans:

services:

  frontend:
    build: ./frontend/config
    container_name: ft_frontend
    ports:
      - "443:443"
      - "4009:80"
    volumes:
      - ./frontend/app:/var/www
    networks:
      - trans
    environment:
      - BACKEND_HOST=host.docker.internal


  db:
    image: postgres:latest
    container_name: ft_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5432:5432"
    restart: always
    networks:
      - trans

  redis:
    image: redis:latest
    container_name: ft_redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "6379:6379"
    networks:
      - trans

  # game_loop:
  #   build: ./game_loop
  #   container_name: ft_game_loop
  #   environment:
  #     - BACKEND_HOST=localhost
  #     - BACKEND_PORT=${BACKEND_PORT}
  #     - REDIS_PORT=${REDIS_PORT}
  #     - REDIS_HOST=redis
  #   networks:
  #     - trans
  #   depends_on:
  #     - backend


# docker stop $(docker ps -a -q)
# docker rm $(docker ps -a -q)
# docker rmi $(docker images -q)
# docker network prune -f
# docker volume prune -f
# docker system prune -a --volumes
# docker volume rm ft_transcendence_backend-files ft_transcendence_frontend-files
