# Generated by Django 5.0.6 on 2024-05-31 14:50
## migrate nao esta salvando

from django.db import migrations

def create_users(apps, schema_editor):
	nomes = [
		"Ana", "Bruno", "Carla", "Daniel", "Eduardo", "Fernanda", "Gabriel", "Helena", "Igor", "Juliana",
		"Lucas", "Mariana", "Natalia", "Otavio", "Paula", "Rafael", "Sofia", "Tiago", "Vanessa", "Yuri",
		"Alice", "Bernardo", "Camila", "Diego", "Elisa", "Felipe", "Giovana", "Hugo", "Isabela", "João",
		"Larissa", "Matheus", "Nicole", "Pedro", "Renata", "Samuel", "Tatiana", "Vitor", "Zoe", "Alexandre",
		"Beatriz", "Cristiano", "Débora", "Emilio", "Fábio", "Gustavo", "Heloísa"
	]

	apelidos = [
		"Nana", "BrunoB", "Cacá", "Dani", "Dudu", "Fê", "Biel", "Lena", "Iggy", "Ju",
		"Lu", "Mari", "Nati", "Tavinho", "Paulette", "Rafa", "Sofi", "Titi", "Nessa", "Yuyu",
		"Ali", "Bê", "Cami", "Dieguito", "Lili", "Lipe", "Gigi", "Huguinho", "Isa", "Joca",
		"Lara", "Matt", "Nica", "Pepê", "Rê", "Samuca", "Tati", "Vitinho", "Zezé", "Alex",
		"Bia", "Cris", "Debs", "Milo", "Fabinho", "Gus", "Helô"
	]

	User = apps.get_model('users', 'User')
	for i, name in enumerate(nomes):
		User.objects.create(name=name, nickname=apelidos[i])


class Migration(migrations.Migration):

	dependencies = [
		('users', '0001_initial'),
	]

	operations = [
		migrations.RunPython(create_users),
	]
