# Generated by Django 5.0.6 on 2024-05-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('ranked', 'ranked'), ('normal', 'normal')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match', models.ManyToManyField(blank=True, related_name='matchTournament', to='users.match')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInTournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentMath', to='users.tournament'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=25)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('online', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(blank=True, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, through='users.PlayerInTournament', to='users.user'),
        ),
        migrations.AddField(
            model_name='playerintournament',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('winner', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('Match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, through='users.MatchPlayer', to='users.user'),
        ),
    ]
