# Generated by Django 5.0.6 on 2024-05-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]

