# Generated by Django 5.0.6 on 2024-07-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='number_players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='total_rounds',
        ),
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('friendly', 'friendly'), ('semi-final', 'semi-final'), ('final', 'final')], default='friendly', max_length=10),
        ),
        migrations.DeleteModel(
            name='TournamentBracket',
        ),
        migrations.DeleteModel(
            name='TournamentPlayer',
        ),
    ]
