# Generated by Django 5.0.6 on 2024-07-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
