# Generated by Django 5.0.6 on 2024-08-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_tournamentplayer_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('random', 'Random'), ('semi_final', 'Semi-Final'), ('final', 'Final')], default='random', max_length=10),
        ),
    ]
