# Generated by Django 5.0.6 on 2024-05-31 19:25

from django.db import migrations


def create_users(apps, schema_editor):
	User = apps.get_model('users', 'User')
	for i in range(1, 11):
		User.objects.create(name=f'User{i}', nickname=f'Nickname{i}')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
		migrations.RunPython(create_users),
    ]
