# Generated by Django 5.0.6 on 2024-06-30 20:19

from django.db import migrations
from django.db import migrations
import random


def create_matches_random(user1, user2, apps):
    MatchPlayer = apps.get_model('tournament', 'MatchPlayer')
    Match = apps.get_model('tournament', 'Match')

    for i in range(0, 10):
        match = Match.objects.create()
        score1 = random.randint(0, 10)
        score2 = random.randint(0, 10)
        if (score1 > score2):
            MatchPlayer.objects.create(match=match, user=user1, score=score1, winner=True)
            MatchPlayer.objects.create(match=match, user=user2, score=score2)
            user1.winners += 1
            user2.losses += 1

        else :
            MatchPlayer.objects.create(match=match, user=user2, score=score2, winner=True)
            MatchPlayer.objects.create(match=match, user=user1, score=score1)

            user2.winners += 1
            user1.losses += 1
        user1.save()
        user2.save()


def add_amigos(users, apps):
    friendship = apps.get_model('users', 'Friendship')
    for user in users:
        for user2 in users:
            if user != user2:
                friendship.objects.create(from_user=user, to_user=user2, status='accepted')


def populate_data(apps, schema_editor):
    #Modelos

    User = apps.get_model('users', 'User')
    friendship = apps.get_model('users', 'Friendship')


    # Criando usuários
    wagraton = User.objects.create(username='wwallas-', nickname='bankai', avatar='https://geekdama.com/wp-content/uploads/2023/04/one-piece-luffy-sorriso-sorrindo-postcover.jpg')
    emanuel = User.objects.create(username='etomiyos', nickname='caramelo', avatar='https://i.ytimg.com/vi/MgGoe6_xiiA/maxresdefault.jpg')
    camila = User.objects.create(username='clourenc', nickname='NEN CONTO', avatar='https://i.ytimg.com/vi/MgGoe6_xiiA/maxresdefault.jpg')
    daniel = User.objects.create(username='dbrandao', nickname='Falido', avatar='https://i.ytimg.com/vi/MgGoe6_xiiA/maxresdefault.jpg')
    for i in range(0, 10):
        User.objects.create(username=f'user{i}', nickname=f'user{i}', avatar=f'https://picsum.photos/id/{i}/200/300')


    # Criando partidas
    create_matches_random(apps=apps, user1=wagraton, user2=emanuel)
    create_matches_random(apps=apps, user1=wagraton, user2=daniel)
    create_matches_random(apps=apps, user1=camila, user2=daniel)


    ##Adicionado amigos
    add_amigos(users=[wagraton, emanuel, camila, daniel], apps=apps)



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data)
    ]
