on: [push, pull_request]

jobs:
  continue-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          cd backend
          ls -la
          pip install -r requirements.txt
          python manage.py test users
