name: run-users-tests

on: [push, pull_request]

jobs:
  continue-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: cd backend
      - run: ls -la
      - run: pip install -r requirements.txt
      - run: python manage.py test users
